### ISSUE TITLE
hello， i have a very difficult problem。。。。

### ISSUE THREAD

**Issue by fumengame** [BlackMATov/unity-iso-tools#5]
I use two isoObjects to assemble an irregular object. I referred to the source code of the snapping function in your editor and implemented the snapping during runtime. 
however，I want to implement a special requirement. When I move a isoObject, it won't snap to the joint of the two isoObjects, but move smoothly along the line.
Just like the picture below, when I want it to move, it won't be affected by the joint and will move along the edges of the two objects.

**Comment by fumengame** [comment]
![mmexport1727193041254.png](https://github.com/user-attachments/assets/8cc13721-fdfb-42da-878f-22417982efe6)

**Comment by BlackMATov** [comment]
Yeah, it will probably be very tricky. And I have no plans to add such a feature to the editor or runtime. Also, I would not recommend basing your solution on my editor code, because it is a bit hackish and editor-only after all. A specific solution for your game may be better and more suitable for you and your project, I believe.
